Don't require XML 2 HTML.
	* bison++.in: Be less strict when building the html output.

git-svn-id: https://svn.gostai.com/svn/common/project-template/trunk@1441 f9a80dcf-8710-0410-9714-9a4fb6817a1c

diff --git a/build-aux/bison++.in b/build-aux/bison++.in
--- a/build-aux/bison++.in
+++ b/build-aux/bison++.in
@@ -47,9 +47,12 @@ $BISON $options $input_base -o $output_base --xml
 status=$?
 set -e
 
-# Whatever happens, create the html output file.
-xsltproc $($BISON --print-datadir)/xslt/xml2xhtml.xsl $output_base_noext.xml \
-  >$output_base_noext.html
+# Whatever happens, create the html output file.  If we can.
+xml2html="xsltproc $($BISON --print-datadir)/xslt/xml2xhtml.xsl"
+if ! $xml2html $output_base_noext.xml >$output_base_noext.html; then
+  echo >&2 "$0: cannot convert XML report to HTML"
+  rm $output_base_noext.html
+fi
 
 # fix_bison_output FILE
 # ---------------------
