doc/local.mk.
	* doc/Makefile.am: Rename as...
	* doc/local.mk: this.
	* Makefile.am, configure.ac, doc/doxygen.sh.in: Adjust.

diff --git a/doc/doxygen.sh.in b/doc/doxygen.sh.in
--- a/doc/doxygen.sh.in
+++ b/doc/doxygen.sh.in
@@ -1,28 +1,46 @@
 #! /bin/sh
-# Generate the file doxygen.h and Doxyfile to tweak Doxygen.
 
-echo '/**
- * \mainpage' >doxygen.h
-for f in README AUTHORS NEWS INSTALL TODO THANKS LINKS ChangeLog LICENSE; do
-    if [ -f "@top_srcdir@/$f" ]; then
-      echo " * \section $f" >>doxygen.h
-      cat "@top_srcdir@/$f" | sed '1s/^/<tt>/;
-                                   s/^[ 	]*\*/\\li/;
-                                   s/^/ * /;
-                                   s/\\\([^a-zA-Z]\)/\\\\\1/g;
-                                   s/\\mainpage/\\\\mainpage/g;
-                                   s/\\file/\\\\file/g;
-                                   s/@mainpage/\\@mainpage/g;
-                                   s/@file/\\@file/g;
-                                   /^ \* $/! s/$/<br>/;
-                                   /^ \* $/  s/$/\
+# Generate the file doxygen.h and Doxyfile to tweak Doxygen in
+# directory $1.
+
+case $1 in
+  ('') echo >&2 "$0: missing argument: output directory"
+     exit 1
+     ;;
+  (*) dir=$1;;
+esac
+
+# Generate the contents of doxygen.h.
+doxygen_h ()
+{
+  echo '/**
+ * \mainpage'
+  for f in README AUTHORS NEWS INSTALL TODO THANKS LINKS ChangeLog LICENSE
+  do
+    if test -f "@top_srcdir@/$f"; then
+      echo " * \section $f"
+      sed -e '1s/^/<tt>/;
+              s/^[	 ]*\*/\\li/;
+              s/^/ * /;
+              s/\\\([^a-zA-Z]\)/\\\\\1/g;
+              s/\\mainpage/\\\\mainpage/g;
+              s/\\file/\\\\file/g;
+              s/@mainpage/\\@mainpage/g;
+              s/@file/\\@file/g;
+              /^ \* $/! s/$/<br>/;
+              /^ \* $/  s/$/\
  */;
-                                   $s@$@</tt>@' >>doxygen.h;
-    fi;
-done;
-echo '*/' >>doxygen.h
+              $s@$@</tt>@'                  \
+            "@top_srcdir@/$f"
+    fi
+  done
+  echo '*/'
+}
 
-cat >Doxyfile <<_ACEOF
+# Generate the contents of Doxyfile.
+Doxyfile ()
+{
+  cat <<EOF
 # Doxyfile configuration file generated by make doc
 PROJECT_NAME           = "@PACKAGE_NAME@"
 PROJECT_NUMBER         = "@PACKAGE_VERSION@"
@@ -74,10 +92,10 @@ WARN_IF_UNDOCUMENTED   = YES
 WARN_IF_DOC_ERROR      = YES
 WARN_NO_PARAMDOC       = YES
 WARN_FORMAT            = "\$file:\$line: \$text"
-INPUT                  = @top_srcdir@/src ./doxygen.h
+INPUT                  = @top_srcdir@/src $dir/doxygen.h
 FILE_PATTERNS          = *.c *.cpp *.cc *.cxx *.h *.hh *.hpp *.hcc *.hxx *.C
 RECURSIVE              = YES
-EXCLUDE                = 
+EXCLUDE                =
 EXCLUDE_SYMLINKS       = NO
 EXCLUDE_PATTERNS       = */tests/*
 SOURCE_BROWSER         = YES
@@ -115,7 +133,7 @@ PERLMOD_LATEX          = NO
 ENABLE_PREPROCESSING   = YES
 MACRO_EXPANSION        = NO
 SEARCH_INCLUDES        = YES
-PERL_PATH              = `which perl`
+PERL_PATH              = $(which perl)
 CLASS_DIAGRAMS         = YES
 HIDE_UNDOC_RELATIONS   = NO
 SEARCHENGINE           = NO
@@ -134,4 +152,11 @@ MAX_DOT_GRAPH_HEIGHT   = 1024
 DOT_MULTI_TARGETS      = YES
 GENERATE_LEGEND        = YES
 DOT_CLEANUP            = YES
-_ACEOF
+EOF
+}
+
+## ------ ##
+## Main.  ##
+## ------ ##
+doxygen_h >$dir/doxygen.h
+Doxyfile  >$dir/Doxyfile
