Add and call version and help in uinstall.
	* sdk/uinstall: Here.
	Move "installdir" before get_options.

diff --git a/sdk/uinstall.in b/sdk/uinstall.in
--- a/sdk/uinstall.in
+++ b/sdk/uinstall.in
@@ -1,5 +1,97 @@
 @UMAKE_COMMON@
 
+usage ()
+{
+    cat <<EOF
+Usage: $me <install_dir>
+
+General options:
+  -h, --help           display this help and exit successfully
+  -v, --version        display version information and exit successfully
+
+EOF
+
+  exit 0
+}
+
+version ()
+{
+  cat <<\EOF
+URBI Make @PACKAGE_VERSION@
+$Id$
+EOF
+  exit 0
+}
+
+installdir=
+
+get_options ()
+{
+  # Push a token among the arguments that will be used to notice when we
+  # ended options/arguments parsing.
+  # Use "set dummy ...; shift" rather than 'set - ..." because on
+  # Solaris set - turns off set -x (but keeps set -e).
+  # Use ${1+"$@"} rather than "$@" because Digital Unix and Ultrix 4.3
+  # still expand "$@" to a single argument (the empty string) rather
+  # than nothing at all.
+  arg_sep="$$--$$"
+  set dummy ${1+"$@"} "$arg_sep"; shift
+
+  # Parse command line arguments.
+  while test x"$1" != x"$arg_sep"
+  do
+    # Handle --option=value by splitting apart and putting back on argv.
+    case $1 in
+      --*=*)
+	opt=`echo "$1" | sed -e 's/=.*//'`
+	val=`echo "$1" | sed -e 's/[^=]*=//'`
+	shift
+	set dummy "$opt" "$val" ${1+"$@"}; shift
+	;;
+    esac
+
+    case $1 in
+      -h | --help   ) usage;;
+      -v | --version) version;;
+
+      --) # What remains are not options.
+	shift
+	while test x"$1" != x"$arg_sep"
+	do
+	    set dummy ${1+"$@"} "$1"; shift
+	    shift
+	done
+	break
+	;;
+      -*)
+	error 2 "Unknown or ambiguous option \`$1'." \
+	      "Try \`--help' for more information."
+	;;
+      *) set dummy ${1+"$@"} "$1"; shift;;
+     esac
+     shift
+  done
+  # Pop the token
+  shift
+
+  # Interpret remaining command line args as filenames.
+  case $# in
+   0)
+    error 2 "Missing install directory on command line."
+    ;;
+   1)
+    installdir=$1
+    ;;
+   *)
+    installdir=$1
+    report "Extra unused arguments after install directory."
+    ;;
+  esac
+}
+
+get_options "$@"
+initialize
+
 dir=$medir
 
 # origin install dir
@@ -12,7 +104,6 @@ currentdir=$(cd $currentdir && pwd)
 currentdir="${currentdir%/bin*}"
 
 # Test install directory existency
-installdir=$1
 if test ! -d "$installdir"; then
   mkdir -p "$installdir"
 fi
